# Generated by Django 4.0.1 on 2022-03-08 04:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='client/image')),
                ('active', models.BooleanField(default=False)),
                ('work_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.category')),
            ],
        ),
    ]
