# Generated by Django 4.0.1 on 2022-03-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_clientsfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCorporateClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='corporate/client')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
