# Generated by Django 4.0.1 on 2022-03-06 14:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('year_in_school', models.CharField(choices=[('B2B', 'B2B Lead Generation'), ('LLG', 'Linkedin Lead Generation'), ('BELBV', 'Bulk Email List building and Verification'), ('DEWR', 'Data Entry and Web Research'), ('REST', 'Real Estate Skip Tracing')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='LeadGeneration',
        ),
    ]
